### PR TITLE
changed

### PR DESCRIPTION
**Pull request by jepetolee**
make new repos

### CODE REVIEW

**Review by Dongyeongkim — CHANGES_REQUESTED** [review]
.pyc files and other files seem to be not good. need to change it

**Comment by jepetolee** [comment]
had just deleted.

**Review by jepetolee — COMMENTED** [review]
add module types on LIF  model

**Comment by Dongyeongkim** [comment]
Need to change some path problem by relative path as Junho Yeo did.

**Comment by Dongyeongkim** [comment]
Open New pull request

**Pull request closed without merging**
